### ISSUE TITLE
Entering more information in Eclipse, in stead of in the JADE GUI

### ISSUE THREAD

**Issue by T06303122** [NinoxDz/JADE-BookTrading#1]
(not really an issue more a point of discussion)

Hey, Thank you for your nice extension to the book trading example. I was very exited when I saw you made agents in the main class rather than in the run configuration - arguments. Unfortunately, now everytime you run an example you'll have to manually fill in book names and prices. Would it not be so much more convenient to be able to do that in the Main as well?

I've been trying to figure out how to do this but I was wondering whether you might have a suggestion on it? This would make it possible to set up the entire environment and all the agents in Eclipse and to run the simulation in the JADE Gui.

So would you know how to enter the arguments (booknames and prices) when created the agents in Eclipse ?

**Comment by NinoxDz** [comment]
Hey,
Thank you for your message,

I haven't had enough time to run the code again and give you a proper answer, but I have taken a look on the code here in GitHub.

You have a function in the BookSellerAgent that is called updateCatalogue, you can call it in the main function after the agent creation, it takes as parameters (String title, int price) and you can create each agent catalogue in the main function, and if you wanna the GUI where you can update the catalogue to don't show you can comment those two lines:	32-myGui = new BookSellerGui(this);		33-myGui.showGui(); from BookSellerAgent.java.

Also if you wanna do the same work with the buyer agent, where you give it the book that he must try to buy in the main function, you need to create the agent buyer in the main class and pass him the book that he should try to buy as a parameters argument, or you should add a variable that is called targetBookTitle as a class attribute, then you create a function that will set it, and then edit the setup function to use the class attribute targetBookTitle instead of using the passed argument.

i hope that my answer could help you,
and sorry again for the delayed answer,
if you have any other idea feel free to comment it here.
